package com.dispatchtrack.studentmanagement.repository;

import com.dispatchtrack.studentmanagement.entity.Student;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.Optional;

/**
 * Repository layer for {@link Student}.
 *
 * Extending {@link JpaRepository} gives us CRUD methods (save, findById,
 * findAll, deleteById, ...) for free, generated by Spring Data JPA at
 * runtime - no implementation class needed.
 */
@Repository
public interface StudentRepository extends JpaRepository<Student, Long> {

    /**
     * Derived query method - Spring Data JPA generates the implementation
     * from the method name alone. Used to enforce/check email uniqueness.
     */
    Optional<Student> findByEmail(String email);

    boolean existsByEmail(String email);
}
